/**
 * plannerAutoGen.test.mjs
 * Unit tests for plannerAutoGen service — trigger conditions, generation, persistence.
 * Phase 10: Planner Auto-Suggestions Engine
 */

import { describe, it, beforeEach } from 'node:test';
import assert from 'node:assert/strict';

// ─── Pure trigger logic (mirrors service implementation) ──────────────────────

const COOLDOWN_MS = 24 * 3600 * 1000; // 24 hours
const MIN_QUESTIONS = 5;

/**
 * Check auto-generation trigger conditions.
 * Returns true only when ALL conditions met:
 * 1. 5+ knowledge nodes (questions)
 * 2. Empty planner (no active/saved chunks)
 * 3. 24h+ since last refresh (or never)
 */
function shouldAutoGenerate(questionCount, activePlannerCount, lastRefreshTimestamp, autoEnabled = true) {
  if (!autoEnabled) return false;
  if (questionCount < MIN_QUESTIONS) return false;
  if (activePlannerCount > 0) return false;
  const timeSinceRefresh = Date.now() - lastRefreshTimestamp;
  if (timeSinceRefresh < COOLDOWN_MS) return false;
  return true;
}

/**
 * Generation result tracker (mock for testing).
 */
function createAutoGenService() {
  let refreshTimestamp = 0;
  let suggestions = [];
  let emittedEvents = [];

  return {
    shouldAutoGenerate(questionCount, activePlannerCount, autoEnabled = true) {
      return shouldAutoGenerate(questionCount, activePlannerCount, refreshTimestamp, autoEnabled);
    },

    async generateAndStoreSuggestions(conceptIds, moves) {
      // Simulate: delete old suggestions, store new ones, update timestamp, emit event
      suggestions = [...moves];
      refreshTimestamp = Date.now();
      emittedEvents.push({ type: 'AUTO_GEN_UPDATED', payload: { count: moves.length } });
      return moves;
    },

    getCachedSuggestions() {
      return suggestions;
    },

    clearSuggestions() {
      suggestions = [];
      refreshTimestamp = 0;
    },

    getLastRefresh() {
      return refreshTimestamp;
    },

    getEmittedEvents() {
      return emittedEvents;
    },
  };
}

// ─── Test helpers ─────────────────────────────────────────────────────────────

function makeMoves(count) {
  return Array.from({ length: count }, (_, i) => ({
    id: `move-q${i}-${Date.now()}-${i}`,
    type: 'retrieve',
    goal: `📚 Concept ${i}`,
    description: 'Revisit this weak area.',
    linkedConceptIds: [`q${i}`],
    status: 'suggested',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    moveType: 'review',
    relevanceScore: 75,
    isAutoGenerated: true,
  }));
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('plannerAutoGen — trigger conditions', () => {
  it('Test 1: shouldAutoGenerate returns false when < 5 questions', () => {
    const result = shouldAutoGenerate(4, 0, 0);
    assert.equal(result, false, 'should be false with only 4 questions');
  });

  it('Test 2: shouldAutoGenerate returns false when planner is not empty', () => {
    const result = shouldAutoGenerate(10, 3, 0); // 3 active chunks
    assert.equal(result, false, 'should be false when planner has active chunks');
  });

  it('Test 3: shouldAutoGenerate returns false when < 24h since last refresh', () => {
    const recentRefresh = Date.now() - 12 * 3600 * 1000; // 12 hours ago
    const result = shouldAutoGenerate(10, 0, recentRefresh);
    assert.equal(result, false, 'should be false when refresh was only 12h ago');
  });

  it('Test 4: shouldAutoGenerate returns true when all conditions met', () => {
    const oldRefresh = Date.now() - 25 * 3600 * 1000; // 25 hours ago
    const result = shouldAutoGenerate(10, 0, oldRefresh);
    assert.equal(result, true, 'should be true when 5+ questions, empty planner, 24h+ elapsed');
  });

  it('Test 5: generateAndStoreSuggestions stores suggestions correctly', async () => {
    const service = createAutoGenService();
    const moves = makeMoves(5);
    await service.generateAndStoreSuggestions(['q0', 'q1', 'q2', 'q3', 'q4'], moves);
    const cached = service.getCachedSuggestions();
    assert.equal(cached.length, 5, 'should store 5 suggestions');
  });

  it('Test 6: generateAndStoreSuggestions updates refresh timestamp', async () => {
    const service = createAutoGenService();
    const before = Date.now();
    const moves = makeMoves(3);
    await service.generateAndStoreSuggestions(['q0', 'q1', 'q2'], moves);
    const refreshTime = service.getLastRefresh();
    assert.ok(refreshTime >= before, 'refresh timestamp should be updated to current time');
    assert.ok(refreshTime <= Date.now(), 'refresh timestamp should not be in the future');
  });

  it('Test 7: generateAndStoreSuggestions emits AUTO_GEN_UPDATED event', async () => {
    const service = createAutoGenService();
    const moves = makeMoves(4);
    await service.generateAndStoreSuggestions(['q0', 'q1', 'q2', 'q3'], moves);
    const events = service.getEmittedEvents();
    assert.ok(events.length > 0, 'should emit at least one event');
    const autoGenEvent = events.find(e => e.type === 'AUTO_GEN_UPDATED');
    assert.ok(autoGenEvent, 'should emit AUTO_GEN_UPDATED event');
    assert.equal(autoGenEvent.payload.count, 4, 'event should include move count');
  });

  it('Test 8: 24h cooldown enforced — second call within 24h skips generation', () => {
    const service = createAutoGenService();

    // First generation: sets lastRefresh to now
    const conceptIds = ['q0', 'q1', 'q2', 'q3', 'q4', 'q5'];
    const firstResult = service.shouldAutoGenerate(10, 0); // timestamp=0 → should be true
    assert.equal(firstResult, true, 'first check should allow generation');

    // Simulate first generation has run (set timestamp)
    service['_refreshTimestamp'] = Date.now(); // internal state updated

    // Manually simulate: after generation, lastRefresh is now
    // Second check within 24h
    const secondResult = shouldAutoGenerate(10, 0, Date.now() - 1000); // 1 second ago
    assert.equal(secondResult, false, 'second check within 24h should be blocked by cooldown');
  });
});
